=begin comment

Marketcheck Cars API

<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::MarketcheckCarsApi::Object::Build;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use WWW::MarketcheckCarsApi::Object::Number;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#Describes the Car specification
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Marketcheck Cars API

<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::MarketcheckCarsApi::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'Describes the Car specification',
                                  class => 'Build',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'year' => {
    	datatype => 'Number',
    	base_name => 'year',
    	description => 'Year of the Car',
    	format => '',
    	read_only => '',
    		},
    'make' => {
    	datatype => 'string',
    	base_name => 'make',
    	description => 'Car Make',
    	format => '',
    	read_only => '',
    		},
    'model' => {
    	datatype => 'string',
    	base_name => 'model',
    	description => 'Car model',
    	format => '',
    	read_only => '',
    		},
    'trim' => {
    	datatype => 'string',
    	base_name => 'trim',
    	description => 'Trim of the car',
    	format => '',
    	read_only => '',
    		},
    'body_type' => {
    	datatype => 'string',
    	base_name => 'body_type',
    	description => 'Body type of the car',
    	format => '',
    	read_only => '',
    		},
    'vehicle_type' => {
    	datatype => 'string',
    	base_name => 'vehicle_type',
    	description => 'Vehicle type of the car',
    	format => '',
    	read_only => '',
    		},
    'drivetrain' => {
    	datatype => 'string',
    	base_name => 'drivetrain',
    	description => 'Drivetrain of the car',
    	format => '',
    	read_only => '',
    		},
    'fuel_type' => {
    	datatype => 'string',
    	base_name => 'fuel_type',
    	description => 'Fuel type of the car',
    	format => '',
    	read_only => '',
    		},
    'made_in' => {
    	datatype => 'string',
    	base_name => 'made_in',
    	description => 'Made in of the car',
    	format => '',
    	read_only => '',
    		},
    'engine' => {
    	datatype => 'string',
    	base_name => 'engine',
    	description => 'Engine of the car',
    	format => '',
    	read_only => '',
    		},
    'engine_block' => {
    	datatype => 'string',
    	base_name => 'engine_block',
    	description => 'Engine block of the car',
    	format => '',
    	read_only => '',
    		},
    'engine_size' => {
    	datatype => 'string',
    	base_name => 'engine_size',
    	description => 'Engine size of the car',
    	format => '',
    	read_only => '',
    		},
    'engine_measure' => {
    	datatype => 'string',
    	base_name => 'engine_measure',
    	description => 'Engine block of the car',
    	format => '',
    	read_only => '',
    		},
    'engine_aspiration' => {
    	datatype => 'string',
    	base_name => 'engine_aspiration',
    	description => 'Engine aspiration of the car',
    	format => '',
    	read_only => '',
    		},
    'transmission' => {
    	datatype => 'string',
    	base_name => 'transmission',
    	description => 'Transmission of the car',
    	format => '',
    	read_only => '',
    		},
    'doors' => {
    	datatype => 'Number',
    	base_name => 'doors',
    	description => 'No of doors of the car',
    	format => '',
    	read_only => '',
    		},
    'cylinders' => {
    	datatype => 'Number',
    	base_name => 'cylinders',
    	description => 'No of cylinders of the car',
    	format => '',
    	read_only => '',
    		},
    'steering_type' => {
    	datatype => 'string',
    	base_name => 'steering_type',
    	description => 'Steering type of the car',
    	format => '',
    	read_only => '',
    		},
    'antibrake_sys' => {
    	datatype => 'string',
    	base_name => 'antibrake_sys',
    	description => 'Antibrake system of the car',
    	format => '',
    	read_only => '',
    		},
    'tank_size' => {
    	datatype => 'string',
    	base_name => 'tank_size',
    	description => 'Tank size of the car',
    	format => '',
    	read_only => '',
    		},
    'overall_height' => {
    	datatype => 'string',
    	base_name => 'overall_height',
    	description => 'Overall height of the car',
    	format => '',
    	read_only => '',
    		},
    'overall_length' => {
    	datatype => 'string',
    	base_name => 'overall_length',
    	description => 'Overall length of the car',
    	format => '',
    	read_only => '',
    		},
    'overall_width' => {
    	datatype => 'string',
    	base_name => 'overall_width',
    	description => 'Overall width of the car',
    	format => '',
    	read_only => '',
    		},
    'std_seating' => {
    	datatype => 'string',
    	base_name => 'std_seating',
    	description => 'Std seating of the car',
    	format => '',
    	read_only => '',
    		},
    'highway_miles' => {
    	datatype => 'string',
    	base_name => 'highway_miles',
    	description => 'Highway miles of the car',
    	format => '',
    	read_only => '',
    		},
    'city_miles' => {
    	datatype => 'string',
    	base_name => 'city_miles',
    	description => 'City miles of the car',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'year' => 'Number',
    'make' => 'string',
    'model' => 'string',
    'trim' => 'string',
    'body_type' => 'string',
    'vehicle_type' => 'string',
    'drivetrain' => 'string',
    'fuel_type' => 'string',
    'made_in' => 'string',
    'engine' => 'string',
    'engine_block' => 'string',
    'engine_size' => 'string',
    'engine_measure' => 'string',
    'engine_aspiration' => 'string',
    'transmission' => 'string',
    'doors' => 'Number',
    'cylinders' => 'Number',
    'steering_type' => 'string',
    'antibrake_sys' => 'string',
    'tank_size' => 'string',
    'overall_height' => 'string',
    'overall_length' => 'string',
    'overall_width' => 'string',
    'std_seating' => 'string',
    'highway_miles' => 'string',
    'city_miles' => 'string'
} );

__PACKAGE__->attribute_map( {
    'year' => 'year',
    'make' => 'make',
    'model' => 'model',
    'trim' => 'trim',
    'body_type' => 'body_type',
    'vehicle_type' => 'vehicle_type',
    'drivetrain' => 'drivetrain',
    'fuel_type' => 'fuel_type',
    'made_in' => 'made_in',
    'engine' => 'engine',
    'engine_block' => 'engine_block',
    'engine_size' => 'engine_size',
    'engine_measure' => 'engine_measure',
    'engine_aspiration' => 'engine_aspiration',
    'transmission' => 'transmission',
    'doors' => 'doors',
    'cylinders' => 'cylinders',
    'steering_type' => 'steering_type',
    'antibrake_sys' => 'antibrake_sys',
    'tank_size' => 'tank_size',
    'overall_height' => 'overall_height',
    'overall_length' => 'overall_length',
    'overall_width' => 'overall_width',
    'std_seating' => 'std_seating',
    'highway_miles' => 'highway_miles',
    'city_miles' => 'city_miles'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
