=begin comment

Marketcheck Cars API

<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::MarketcheckCarsApi::GraphsApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::MarketcheckCarsApi::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::MarketcheckCarsApi::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::MarketcheckCarsApi::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# get_price_miles_plot_data
#
# Price, Miles plots data for given criteria
# 
# @param string $car_type Car type to get the scatter plot data for (required)
# @param string $api_key The API Authentication Key. Mandatory with all API calls. (optional)
# @param string $vin VIN as a reference to the type of car for which plot data is to be returned (optional)
# @param string $year Year of the car (optional)
# @param string $make Make of the car (optional)
# @param string $model Model of the Car (optional)
# @param string $trim Trim of the Car (optional)
# @param int $rows Number of results to return. Default is 1000. Max is 10000 (optional)
{
    my $params = {
    'car_type' => {
        data_type => 'string',
        description => 'Car type to get the scatter plot data for',
        required => '1',
    },
    'api_key' => {
        data_type => 'string',
        description => 'The API Authentication Key. Mandatory with all API calls.',
        required => '0',
    },
    'vin' => {
        data_type => 'string',
        description => 'VIN as a reference to the type of car for which plot data is to be returned',
        required => '0',
    },
    'year' => {
        data_type => 'string',
        description => 'Year of the car',
        required => '0',
    },
    'make' => {
        data_type => 'string',
        description => 'Make of the car',
        required => '0',
    },
    'model' => {
        data_type => 'string',
        description => 'Model of the Car',
        required => '0',
    },
    'trim' => {
        data_type => 'string',
        description => 'Trim of the Car',
        required => '0',
    },
    'rows' => {
        data_type => 'int',
        description => 'Number of results to return. Default is 1000. Max is 10000',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_price_miles_plot_data' } = { 
    	summary => 'Price, Miles plots data for given criteria',
        params => $params,
        returns => 'ARRAY[PlotPoint]',
        };
}
# @return ARRAY[PlotPoint]
#
sub get_price_miles_plot_data {
    my ($self, %args) = @_;

    # verify the required parameter 'car_type' is set
    unless (exists $args{'car_type'}) {
      croak("Missing the required parameter 'car_type' when calling get_price_miles_plot_data");
    }

    # parse inputs
    my $_resource_path = '/plots';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'api_key'}) {
        $query_params->{'api_key'} = $self->{api_client}->to_query_value($args{'api_key'});
    }

    # query params
    if ( exists $args{'vin'}) {
        $query_params->{'vin'} = $self->{api_client}->to_query_value($args{'vin'});
    }

    # query params
    if ( exists $args{'year'}) {
        $query_params->{'year'} = $self->{api_client}->to_query_value($args{'year'});
    }

    # query params
    if ( exists $args{'make'}) {
        $query_params->{'make'} = $self->{api_client}->to_query_value($args{'make'});
    }

    # query params
    if ( exists $args{'model'}) {
        $query_params->{'model'} = $self->{api_client}->to_query_value($args{'model'});
    }

    # query params
    if ( exists $args{'trim'}) {
        $query_params->{'trim'} = $self->{api_client}->to_query_value($args{'trim'});
    }

    # query params
    if ( exists $args{'car_type'}) {
        $query_params->{'car_type'} = $self->{api_client}->to_query_value($args{'car_type'});
    }

    # query params
    if ( exists $args{'rows'}) {
        $query_params->{'rows'} = $self->{api_client}->to_query_value($args{'rows'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[PlotPoint]', $response);
    return $_response_object;
}

1;
