=begin comment

Marketcheck Cars API

<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::MarketcheckCarsApi::ListingsApi');

my $api = WWW::MarketcheckCarsApi::ListingsApi->new();
isa_ok($api, 'WWW::MarketcheckCarsApi::ListingsApi');

#
# get_listing test
#
{
    my $id = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $result = $api->get_listing(id => $id, api_key => $api_key);
}

#
# get_listing_extra test
#
{
    my $id = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $result = $api->get_listing_extra(id => $id, api_key => $api_key);
}

#
# get_listing_media test
#
{
    my $id = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $result = $api->get_listing_media(id => $id, api_key => $api_key);
}

#
# get_listing_vdp test
#
{
    my $id = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $html = undef; # replace NULL with a proper value
    my $result = $api->get_listing_vdp(id => $id, api_key => $api_key, html => $html);
}

#
# get_summary_report test
#
{
    my $vin = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $result = $api->get_summary_report(vin => $vin, api_key => $api_key);
}

#
# search test
#
{
    my $api_key = undef; # replace NULL with a proper value
    my $latitude = undef; # replace NULL with a proper value
    my $longitude = undef; # replace NULL with a proper value
    my $radius = undef; # replace NULL with a proper value
    my $car_type = undef; # replace NULL with a proper value
    my $seller_type = undef; # replace NULL with a proper value
    my $year = undef; # replace NULL with a proper value
    my $make = undef; # replace NULL with a proper value
    my $model = undef; # replace NULL with a proper value
    my $trim = undef; # replace NULL with a proper value
    my $dealer_id = undef; # replace NULL with a proper value
    my $vin = undef; # replace NULL with a proper value
    my $source = undef; # replace NULL with a proper value
    my $body_type = undef; # replace NULL with a proper value
    my $body_subtype = undef; # replace NULL with a proper value
    my $vehicle_type = undef; # replace NULL with a proper value
    my $vins = undef; # replace NULL with a proper value
    my $taxonomy_vins = undef; # replace NULL with a proper value
    my $ymmt = undef; # replace NULL with a proper value
    my $match = undef; # replace NULL with a proper value
    my $cylinders = undef; # replace NULL with a proper value
    my $transmission = undef; # replace NULL with a proper value
    my $speeds = undef; # replace NULL with a proper value
    my $doors = undef; # replace NULL with a proper value
    my $drivetrain = undef; # replace NULL with a proper value
    my $exterior_color = undef; # replace NULL with a proper value
    my $interior_color = undef; # replace NULL with a proper value
    my $engine = undef; # replace NULL with a proper value
    my $engine_type = undef; # replace NULL with a proper value
    my $engine_aspiration = undef; # replace NULL with a proper value
    my $engine_block = undef; # replace NULL with a proper value
    my $miles_range = undef; # replace NULL with a proper value
    my $price_range = undef; # replace NULL with a proper value
    my $dom_range = undef; # replace NULL with a proper value
    my $sort_by = undef; # replace NULL with a proper value
    my $sort_order = undef; # replace NULL with a proper value
    my $rows = undef; # replace NULL with a proper value
    my $start = undef; # replace NULL with a proper value
    my $facets = undef; # replace NULL with a proper value
    my $stats = undef; # replace NULL with a proper value
    my $country = undef; # replace NULL with a proper value
    my $plot = undef; # replace NULL with a proper value
    my $nodedup = undef; # replace NULL with a proper value
    my $state = undef; # replace NULL with a proper value
    my $city = undef; # replace NULL with a proper value
    my $dealer_name = undef; # replace NULL with a proper value
    my $trim_o = undef; # replace NULL with a proper value
    my $trim_r = undef; # replace NULL with a proper value
    my $dom_active_range = undef; # replace NULL with a proper value
    my $dom_180_range = undef; # replace NULL with a proper value
    my $options = undef; # replace NULL with a proper value
    my $features = undef; # replace NULL with a proper value
    my $result = $api->search(api_key => $api_key, latitude => $latitude, longitude => $longitude, radius => $radius, car_type => $car_type, seller_type => $seller_type, year => $year, make => $make, model => $model, trim => $trim, dealer_id => $dealer_id, vin => $vin, source => $source, body_type => $body_type, body_subtype => $body_subtype, vehicle_type => $vehicle_type, vins => $vins, taxonomy_vins => $taxonomy_vins, ymmt => $ymmt, match => $match, cylinders => $cylinders, transmission => $transmission, speeds => $speeds, doors => $doors, drivetrain => $drivetrain, exterior_color => $exterior_color, interior_color => $interior_color, engine => $engine, engine_type => $engine_type, engine_aspiration => $engine_aspiration, engine_block => $engine_block, miles_range => $miles_range, price_range => $price_range, dom_range => $dom_range, sort_by => $sort_by, sort_order => $sort_order, rows => $rows, start => $start, facets => $facets, stats => $stats, country => $country, plot => $plot, nodedup => $nodedup, state => $state, city => $city, dealer_name => $dealer_name, trim_o => $trim_o, trim_r => $trim_r, dom_active_range => $dom_active_range, dom_180_range => $dom_180_range, options => $options, features => $features);
}


1;
