=begin comment

Marketcheck Cars API

<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::MarketcheckCarsApi::MarketApi');

my $api = WWW::MarketcheckCarsApi::MarketApi->new();
isa_ok($api, 'WWW::MarketcheckCarsApi::MarketApi');

#
# get_averages test
#
{
    my $vin = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $year = undef; # replace NULL with a proper value
    my $make = undef; # replace NULL with a proper value
    my $model = undef; # replace NULL with a proper value
    my $trim = undef; # replace NULL with a proper value
    my $fields = undef; # replace NULL with a proper value
    my $result = $api->get_averages(vin => $vin, api_key => $api_key, year => $year, make => $make, model => $model, trim => $trim, fields => $fields);
}

#
# get_comparison test
#
{
    my $vin = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $result = $api->get_comparison(vin => $vin, api_key => $api_key);
}

#
# get_competition test
#
{
    my $vin = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $result = $api->get_competition(vin => $vin, api_key => $api_key);
}

#
# get_depreciation test
#
{
    my $vin = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $result = $api->get_depreciation(vin => $vin, api_key => $api_key);
}

#
# get_mds test
#
{
    my $vin = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $latitude = undef; # replace NULL with a proper value
    my $longitude = undef; # replace NULL with a proper value
    my $radius = undef; # replace NULL with a proper value
    my $debug = undef; # replace NULL with a proper value
    my $include_sold = undef; # replace NULL with a proper value
    my $result = $api->get_mds(vin => $vin, api_key => $api_key, exact => $exact, latitude => $latitude, longitude => $longitude, radius => $radius, debug => $debug, include_sold => $include_sold);
}

#
# get_popularity test
#
{
    my $year = undef; # replace NULL with a proper value
    my $make = undef; # replace NULL with a proper value
    my $model = undef; # replace NULL with a proper value
    my $trim = undef; # replace NULL with a proper value
    my $body_type = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $stats = undef; # replace NULL with a proper value
    my $result = $api->get_popularity(year => $year, make => $make, model => $model, trim => $trim, body_type => $body_type, api_key => $api_key, stats => $stats);
}

#
# get_trends test
#
{
    my $vin = undef; # replace NULL with a proper value
    my $car_type = undef; # replace NULL with a proper value
    my $api_key = undef; # replace NULL with a proper value
    my $year = undef; # replace NULL with a proper value
    my $make = undef; # replace NULL with a proper value
    my $model = undef; # replace NULL with a proper value
    my $trim = undef; # replace NULL with a proper value
    my $result = $api->get_trends(vin => $vin, car_type => $car_type, api_key => $api_key, year => $year, make => $make, model => $model, trim => $trim);
}


1;
